name: Biletix Etkinlik Çek

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Python kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Kütüphaneleri yükle
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Botu çalıştır
        run: |
          python scrape_biletix.py
          python supabase_upload.py