name: Etkinlik Botu

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'  # Her gün 03:00 UTC (Türkiye saatiyle 06:00)

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Depoyu al
        uses: actions/checkout@v3

      - name: Python kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Kütüphaneleri yükle
        run: |
          pip install requests supabase geopy

      - name: Google Etkinliklerinden çek ve Supabase'e yükle
        env:
          SERPAPI_KEY: ${{ secrets.SERPAPI_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          python scrape_google_events.py | python supabase_upload.py
